### ISSUE TITLE
关于passwall packages SDK版本的问题

### ISSUE THREAD

**Issue by nftbty** [MoetaYuko/openwrt-passwall-build#10]
看到你刚刚在passwall自动编译那边的评论，正好有个问题想问下。
我觉得，其实passwall弄个luci的自动编译就行了，没必要每次编译还要带上packages。一个是你说的版本不全的问题，还有一个用户下载安装也不方便，需要下整个压缩包，再把需要的解压出来。而且每次passwall更新版本号都编译一次packages，但packages可能几天都不更新，而passwall有时候一天要更新几个版本，会造成多个相同版本的重复编译。
我觉得利用好openwrt-passwall-build的opkg源，要方便很多。所以我打算把这个源仓库在passwall安装时就添加到系统，有2个问题想问下：
1. readme里使用的仓库地址是`https://free.nchc.org.tw/osdn`，是否台湾镜像就是大陆访问最快的源了，还有其他备用的稳定的源吗，osdn官网mirrors有个香港的xtom，但是用浏览器访问的话是403。不知道nchc的镜像一般落后官方几个小时。
2. 按你评论说的，不同SDK编译出来可能ABI不兼容。国内的一些第三方op，比如lean的，是要添加snapshots的源吗？
好像这些op除了luci是老的，其他都是跟官方master分支来的，`/etc/openwrt-release`里面也是`DISTRIB_RELEASE='SNAPSHOT'`

PS：刚刚看了一下passwall_packages，发现大部分代理软件都是Go程序了，少数几个c/c++的依赖包，都停更好久了，没有更新的需要。唯一还在更新的C程序就是ChinaDNS-NG。只从packages更新而不是新装passwall的角度来看，应该是不会出现这个兼容性问题的。新安装的麻烦些，确实要考虑这个问题，之后做个测试验证下。

**Comment by MoetaYuko** [comment]
>    readme里使用的仓库地址是`https://free.nchc.org.tw/osdn`，是否台湾镜像就是大陆访问最快的源了，还有其他备用的稳定的源吗，osdn官网mirrors有个香港的xtom，但是用浏览器访问的话是403。不知道nchc的镜像一般落后官方几个小时。

从 osdn 官网直接下载会有个更改镜像的选项，里面只剩 3 个了，nchc 是最快的。时效性不清楚

>   按你评论说的，不同SDK编译出来可能ABI不兼容。国内的一些第三方op，比如lean的，是要添加snapshots的源吗？
>        好像这些op除了luci是老的，其他都是跟官方master分支来的，`/etc/openwrt-release`里面也是`DISTRIB_RELEASE='SNAPSHOT'`

用魔改 op 跟源码一块编译才能杜绝兼容性问题。他们跟官方进度不同步，跟的是 master 但并不是每天都 merge，如果基础库版本恰好跟当前的官方 master 相同的话倒是能兼容，但没有机制去保证这个东西。

此外官方 snapshot 是日更的，今天的 sdk 编译的包完全有可能在昨天的 snapshot rom 上跑不起来，而且也不会有正常用户去用官方的 snapshot rom。所以做 snapshot 的源主要是为了测试 passwall 跟最新 op 的兼容性，而不是真的希望有人去用。

> 
> 
> PS：刚刚看了一下passwall_packages，发现大部分代理软件都是Go程序了，少数几个c/c++的依赖包，都停更好久了，没有更新的需要。唯一还在更新的C程序就是ChinaDNS-NG。只从packages更新而不是新装passwall的角度来看，应该是不会出现这个兼容性问题的。新安装的麻烦些，确实要考虑这个问题，之后做个测试验证下。

非也，go 也是 native 程序，libc 是链接到系统的。本仓库一开始也是只用了一个版本的 sdk，后来发现编译的 v2ray 运行不了才换到了现在的多 sdk 架构 https://github.com/MoetaYuko/openwrt-passwall-build/commit/c96945bfea0b2aecba305b3927330b3dda532526

**Comment by nftbty** [comment]
刚刚用ldd查了下系统上openwrt编译的xray，果然有动态链接到libc。我印象中golang后来应该是全静态链接所有库的，查了一下资料。golang链接到libc应该是cgo的原因，cgo默认开启的，即使程序完全没用到cgo的功能，也会默认动态链接到libc。当然，没有用到cgo的可以关掉。即使用到了cgo，也可以通过参数把libc也一起静态链接。
动态链接libc的程序在有些机器上跑不了倒也不是abi的问题，应该是程序使用较新版本的libc编译，然后运行机器上的libc版本低于编译时的版本。查到的资料是说只要运行机器上的libc版本大于等于编译时的libc版本，就可以正常运行。
说到现在go程序都是全静态链接，做了个测试。把系统上原来xray改名为xray_，然后从组件更新下载所有组件的官方编译发布版。使用ldd查看，brook、hysteria、trojan-go、v2ray、xray都没有任何动态链接，显示**Not a valid dynamic program**。对比2个版本的xray文件，动态链接到libc的版本 23.16MB，官方发布的全静态版 23.44MB，并没有大多少。感觉这些go程序完全可以改成全静态链接。

**Comment by MoetaYuko** [comment]
go 静态链接能在包自己的 makefile 里改吗，会不会涉及 openwrt 内部的某些编译脚本

**Comment by nftbty** [comment]
> go 静态链接能在包自己的 makefile 里改吗，会不会涉及 openwrt 内部的某些编译脚本

应该是可以的，只不过编译参数加点东西，就是看openwrt的go编译参数怎么设置了。看xray的Makefile里面有include `feeds/packages/lang/golang/golang-package.mk`这个文件，分析这个文件应该就能知道怎么加编译参数了。

**Comment by MoetaYuko** [comment]
符号表和调试信息确实没啥用

**Comment by nftbty** [comment]
来回修改测试，发现`GO_PKG_LDFLAGS:=`后面加的参数全部无效，不管是 -s -w，还是 -extldflags '-static'。
看到**golang-package.mk** 里面有`CGO_LDFLAGS="$(TARGET_LDFLAGS)"`以及这么一段
```
GO_PKG_DEFAULT_LDFLAGS= \
	......
	-extldflags '$(patsubst -z%,-Wl$(comma)-z$(comma)%,$(TARGET_LDFLAGS))'
```
于是试着在Makefile里定义`TARGET_LDFLAGS:=-static`，再重新编译，成功得到全静态链接的xray程序。
就是为什么定义在`GO_PKG_LDFLAGS:=`里面就不生效还没找到原因，用V=s编译，查看到编译参数里已成功添加。
