### ISSUE TITLE
[功能请求] 添加对 OpenWrt 23.05 系列的支持

### ISSUE THREAD

**Issue by Effect-Wei** [MoetaYuko/openwrt-passwall-build#12]
截至目前，OpenWrt 项目已经发布了 OpenWrt 23.05.0-rc1，但本项目仍未对其提供支持。

强行使用 22.03 的仓库会缺失依赖项，未测试快照版本对应仓库。

希望作者早日为 OpenWrt 23.05.0-rc1 提供支持，感激不尽。

**Comment by Effect-Wei** [comment]
我大概看了一下，作者的代码似乎已经对 23.05 提供了支持，但 Actions 中部分架构构建不成功导致上传至 osdn 的步骤被跳过了，作者考虑修复一下吗？

**Comment by MoetaYuko** [comment]
openwrt 上游代码存在问题会导致编译错误，均已提交 bug report 或修复补丁。待修复合并后自然就会编译成功

**Comment by zdm9981** [comment]
能否将编译成功的部分同步到源里呢？看了下大部分都编译成功了 只有少部分是失败的

**Comment by MoetaYuko** [comment]
> 能否将编译成功的部分同步到源里呢？看了下大部分都编译成功了 只有少部分是失败的

可以但我懒得改上传脚本（
欢迎PR
