### ISSUE TITLE
Dependency error with OpenWRT 23.05

### ISSUE THREAD

**Issue by mohamadkhalaj** [MoetaYuko/openwrt-passwall-build#13]
Hello, i've upgraded my router to the latest version of openwrt and i tried to install passwall but i got the following error during installation:

 * satisfy_dependencies_for: Cannot satisfy the following dependencies for luci-app-passwall:
 * 	libopenssl1.1
 * opkg_install_cmd: Cannot install package luci-app-passwall.

**Comment by MoetaYuko** [comment]
we don't have builds for 23.05 yet, how did you install?

**Comment by mohamadkhalaj** [comment]
How can i  build it? is it very hard?

**Comment by MoetaYuko** [comment]
https://openwrt.org/docs/guide-developer/toolchain/using_the_sdk

**Comment by mohamadkhalaj** [comment]
Thank you.

**Comment by MoetaYuko** [comment]
you could also grab ipks from action artifacts (e.g. https://github.com/MoetaYuko/openwrt-passwall-build/actions/runs/5231334818) even if the action failed
