### ISSUE TITLE
Collected errors: * opkg_conf_load: Could not lock /var/lock/opkg.lock: Resource temporarily unavailable.

### ISSUE THREAD

**Issue by ahmadElsharawy** [MoetaYuko/openwrt-passwall-build#23]
How can this mistake be avoided ?

 
Model | CJ-Hello HYC-G920
 
Architecture | MediaTek MT7621 ver:1 eco:3
Target Platform | ramips/mt7621
Firmware Version | OpenWrt 23.05.2 r23630-842932a63d / LuCI openwrt-23.05 branch git-23.306.39416-c86c256
Kernel Version | 5.15.137
 

<img width="574" alt="Sketch" src="https://github.com/MoetaYuko/openwrt-passwall-build/assets/67033609/5eea9ce1-4d7b-46ad-93a8-7a61e879bbb5">

**Comment by MoetaYuko** [comment]
this should be reported to upstream.
