### ISSUE TITLE
cant install package

### ISSUE THREAD

**Issue by amirkazemi94** [MoetaYuko/openwrt-passwall-build#28]
my architect is x86_64 when i was try to install package by this command " opkg install luci-app-passwal" the error was occurred:
Unknown package 'luci-app-passwall'.
Collected errors:
 * pkg_hash_check_unresolved: cannot find dependency chinadns-ng for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency dns2socks for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency dns2tcp for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency microsocks for luci-app-passwall
 * pkg_hash_check_unresolved: cannot find dependency tcping for luci-app-passwall
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.

**Comment by MoetaYuko** [comment]
you probably didn't add opkg repository with the correct architecture
