### ISSUE TITLE
all links from sourceforge is broken

### ISSUE THREAD

**Issue by peditx** [moetayuko/openwrt-passwall-build#34]
I think the SourceForge links have changed, and files without the ?viasf=1 suffix can no longer be downloaded.

**Comment by moetayuko** [comment]
Have you tried installing `wget-ssl`? It should automatically handle the redirection.

**Comment by peditx** [comment]
Unfortunately, wget-ssl is not helping with updating the repository to get the package.gz! with opkg update

> opkg update
> Downloading https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/arm_cortex-a7_neon-vfpv4/passwall_luci/Packages.gz
> *** Failed to download the package list from https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/arm_cortex-a7_neon-vfpv4/passwall_luci/Packages.gz

**Comment by moetayuko** [comment]
FYI here's my log:
```
root@OpenWrt:~# opkg update
Downloading https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/x86_64/passwall_luci/Packages.gz
Updated list of available packages in /var/opkg-lists/passwall_luci
Downloading https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/x86_64/passwall_luci/Packages.sig
Signature check passed.
Downloading https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/x86_64/passwall_packages/Packages.gz
Updated list of available packages in /var/opkg-lists/passwall_packages
Downloading https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/x86_64/passwall_packages/Packages.sig
Signature check passed.
Downloading https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/x86_64/passwall2/Packages.gz
Updated list of available packages in /var/opkg-lists/passwall2
Downloading https://master.dl.sourceforge.net/project/openwrt-passwall-build/releases/packages-23.05/x86_64/passwall2/Packages.sig
Signature check passed.
```

**Comment by peditx** [comment]
I'm speaking on behalf of Iranians; over 40 people have reached out to me for help with this matter, and their requests are all identical. We can directly download from SourceForge, but unfortunately, we're encountering issues with routers.

**Comment by moetayuko** [comment]
you gotta figure it out on your own.

opkg is aware of `http_proxy` and `https_proxy` environment variables, so setting up a proxy on another device is a simple solution for first-time install

**Comment by peditx** [comment]
The internet situation in Iran is more complex than you might imagine. Is private communication possible?

**Comment by moetayuko** [comment]
> The internet situation in Iran is more complex than you might imagine. Is private communication possible?

addressing connection issues to SF is out of my scope. you can always manually download the ipk and install them

**Comment by mika2463** [comment]
That route dose work in china and other countries but apparently Iranian networking systems appear to deny direct access to source forge network because of sanctions? Manual installation is a bit complicated then ssh auto install

**Comment by mika2463** [comment]
Found fix i needed to proxy the whole system using another system connected to another router to this router——— Iranian internet is not passing the packages only vpn can let you do that i hope everyone can use this method i got my pass-wall installed
