### ISSUE TITLE
v2ray-plugin missing

### ISSUE THREAD

**Issue by CJayAcopra** [MoetaYuko/openwrt-passwall-build#4]
Good Day Sir!

I am trying to install luci-app-passwall on my raspberry pi openwrt and i cam accross this project of yours, but the problem is the v2ray-plugin is missing on osdn and i cannot install the app, can you pls help me sir. Thank you.

**Comment by MoetaYuko** [comment]
Just checked the build log and v2ray-plugin builds fine for raspberry pi targets. I'm unsure if there's a network error when uploading to osdn, plz wait for the next build to see if it gets fixed.

**Comment by MoetaYuko** [comment]
Should be a network error. You can temp download from artifacts of the last build https://github.com/MoetaYuko/openwrt-passwall-build/actions/runs/1396053639

**Comment by CJayAcopra** [comment]
thank you sir
