### ISSUE TITLE
SSR信息导入不全

### ISSUE THREAD

**Issue by lucktu** [MoetaYuko/openwrt-passwall-build#6]
您好！
       我使用 docker 版 openwrt21（openwrt-21.02.1-x86-64-rootfs.tar.gz），安装以后，使用节点导入的方法加入 SSR 信息时，页面选项导入不全面（没有加密之类的信息），需要手工补全才能用，不知是什么原因？

![001](https://user-images.githubusercontent.com/30952545/151689229-5859a4c2-3976-4810-8131-31c0f8dc77b6.PNG)

另外，建议将 luci-compat 加入主程序的依赖里去，免得乱码。

**Comment by MoetaYuko** [comment]
This project contains just build scripts. All other issues should be reported upstream.

**Comment by lucktu** [comment]
OK，明白了，感谢感谢！！
