### ISSUE TITLE
GitHub Actions workflow缺少并行控制

### ISSUE THREAD

**Issue by zhangyoufu** [MoetaYuko/openwrt-passwall-build#8]
如果上游项目或者本项目频繁提交，可能会有多个Pipeline并行构建。由于构建时间受到多重因素影响，新commit可能会先于老commit完成构建，产物被老commit覆盖。
建议使用[concurrency功能](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency)对release控制并行度

**Comment by MoetaYuko** [comment]
目前的流程是每天定时扫描一次upstream，如果发现更新就打一个tag并触发构建，似乎不存在并行问题？

**Comment by zhangyoufu** [comment]
有一种极端情况：job运行时长超过一天还成功了。不考虑的话那确实无所谓了
