### ISSUE TITLE
Limited storage on router

### ISSUE THREAD

**Issue by Ehsan3500** [MoetaYuko/openwrt-passwall-build#9]
thanks for detailed instructions
my router has limited flash storage (32MB) for pass wall and its dependencies , is there any modified package or other way rather than using Exroot external USB?

**Comment by MoetaYuko** [comment]
This repo contains build scripts of passwall rather than passwall itself, so your issue is out of scope.

My personal suggestion is to rebuild passwall with the minimum dependencies that you actually need. 32MB should be sufficient for passwall luci + v2ray
